flaskProject/blueprints/user.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session, flash, g
from flask_mail import Message
from exts import mail, db
from models import *
import string
import random
from .forms import RegisterForm, LoginForm
from werkzeug.security import generate_password_hash, check_password_hash

bp = Blueprint('user', __name__, url_prefix='/user')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password, password):
                session['user_id'] = user.id
                if user.auto == 1:
                    return redirect('/tmp')
                return redirect('/')
            else:
                flash('邮箱或密码错误！')
                return redirect(url_for('user.login'))
        else:
            flash('邮箱或密码错误！')
            return redirect(url_for('user.login'))


@bp.route("/logout")
def logout():
    # 清除session中所有的数据
    session.clear()
    return redirect(url_for('user.login'))


@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            hash_password = generate_password_hash(password)
            if password == '654321':
                auto = 1
            else:
                auto = 0
            user = UserModel(email=email, username=username, password=hash_password, auto=auto)
            db.session.add(user)
            db.session.commit()
            flash('注册成功！即将跳转到登录页面')
            return redirect(url_for('user.login'))
        else:
            flash('信息有误！')
            return redirect(url_for('user.register'))


@bp.route('/captcha', methods=['POST'])
def get_captcha():
    email = request.form.get('email')
    letters = string.ascii_letters + string.digits
    captcha = "".join(random.sample(letters, 6))
    if email:
        messages = Message(
            subject='【水表系统验证码】',
            recipients=[email],
            body=f'【水表系统】\n您好，您的验证码为\n【{captcha}】\n请不要告诉任何人'
        )
        mail.send(messages)
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.create_time = datetime.now()
            db.session.commit()
        else:
            captcha_model = EmailCaptchaModel(email=email, captcha=captcha)
            db.session.add(captcha_model)
            db.session.commit()
        return jsonify({'code': 200})
    else:
        return jsonify({'code': 400, 'messages': '请输入邮箱'})

flaskProject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet"
          href="{{ url_for('static',filename='bootstrap/bootstrap@4.6.min.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">水表系统</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">首页<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/history">历史数据</a>
                </li>
                <li class="nav-item" ml-2>
                    <form class="form-inline my-2 my-lg-0" method="GET" action="/search">
                        <input class="form-control mr-sm-2" type="search" placeholder="关键字"
                               aria-label="Search" name="q">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索
                        </button>
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user %}
                    <li class="nav-item">
                        <span class="nav-link">{{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block body %}{% endblock %}
</div>
</body>
</html>

flaskProject/templates/history.html
{#{% extends "base.html" %}#}
{##}
{#{% block title %}水表系统-历史记录{% endblock %}#}
{##}
{#{% block head %}#}
{#    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">#}
{#{% endblock %}#}
{##}
{#{% block body %}#}
{#    {% if g.user.auto==0 %}#}
{#        {% for data in datas %}#}
{#            <div class="{{ lis[(datas.index(data))%3] }} divcss-a">#}
{#                <a href="http://127.0.0.1:5000/static/{{ data[0] }}" target="_blank">#}
{#                    <img class="side-question-avatar"#}
{#                         src="{{ url_for('static',filename=data[0]) }}">#}
{#                </a>#}
{#                <br/>#}
{#                {{ data[0] }}#}
{#                <br/>#}
{#                识别结果：{{ data[1] }}#}
{#            </div>#}
{#        {% endfor %}#}
{#    {% endif %}#}
{#    {% if g.user.auto==1 %}#}
{#        {% for data in datas %}#}
{#            <div class="{{ lis[(datas.index(data))%3] }} divcss-a">#}
{#                <a href="http://127.0.0.1:5000/static/{{ data[0] }}" target="_blank">#}
{#                    <img class="side-question-avatar"#}
{#                         src="{{ url_for('static',filename=data[0]) }}">#}
{#                </a>#}
{#                <br/>#}
{#                {{ data[0] }}#}
{#                <br/>#}
{#                识别结果：{{ data[1] }}#}
{#                <br/>#}
{#                <form method="get" action="alte/{{ data[0] }}">#}
{#                    <input type="text" name="alte" id="alte" placeholder="请输入正确数值"#}
{#                           class="side-question-avatar1">#}
{#                    <button type="submit" class="button_search">修订</button>#}
{#                </form>#}
{#                <br/>#}
{#                <form method="get" action="delt/{{ data[0] }}">#}
{#                    <button type="submit" class="divcss-b button_search">删除</button>#}
{#                </form>#}
{#            </div>#}
{#        {% endfor %}#}
{#    {% endif %}#}
{#{% endblock %}#}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>水表系统-历史记录</title>
    <link rel="stylesheet"
          href="{{ url_for('static',filename='bootstrap/bootstrap@4.6.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        {% if g.user.auto==1 %}
            <a class="navbar-brand" href="/tmp">水表系统</a>
        {% endif %}
        {% if g.user.auto==0 %}
            <a class="navbar-brand" href="/">水表系统</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    {% if g.user.auto==1 %}
                        <a class="nav-link" href="/tmp">首页<span class="sr-only">(current)</span></a>
                    {% endif %}
                    {% if g.user.auto==0 %}
                        <a class="nav-link" href="/">首页<span class="sr-only">(current)</span></a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/history">历史数据</a>
                </li>
                <li class="nav-item" ml-2>
                    <form class="form-inline my-2 my-lg-0" method="GET" action="/search">
                        <input class="form-control mr-sm-2" type="search" placeholder="关键字"
                               aria-label="Search" name="q">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索
                        </button>
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user %}
                    <li class="nav-item">
                        <span class="nav-link">{{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% if g.user.auto==0 %}
        {% for data in datas %}
            <div class="{{ lis[(datas.index(data))%3] }} divcss-a">
                <a href="http://127.0.0.1:5000/static/{{ data[0] }}" target="_blank">
                    <img class="side-question-avatar"
                         src="{{ url_for('static',filename=data[0]) }}">
                </a>
                <br/>
                {{ data[0] }}
                <br/>
                识别结果：{{ data[1] }}
            </div>
        {% endfor %}
    {% endif %}
    {% if g.user.auto==1 %}
        {% for data in datas %}
            <div class="{{ lis[(datas.index(data))%3] }} divcss-a">
                <a href="http://127.0.0.1:5000/static/{{ data[0] }}" target="_blank">
                    <img class="side-question-avatar"
                         src="{{ url_for('static',filename=data[0]) }}">
                </a>
                <br/>
                {{ data[0] }}
                <br/>
                识别结果：{{ data[1] }}
                <br/>
                <form method="get" action="alte/{{ data[0] }}">
                    <input type="text" name="alte" id="alte" placeholder="请输入正确数值"
                           class="side-question-avatar1">
                    <button type="submit" class="button_search">修订</button>
                </form>
                <br/>
                <form method="get" action="delt/{{ data[0] }}">
                    <button type="submit" class="divcss-b button_search">删除</button>
                </form>
            </div>
        {% endfor %}
    {% endif %}
</div>
</body>
</html>

flaskProject/templates/index.html
{#{% extends "base.html" %}#}
{##}
{#{% block title %}水表系统-首页{% endblock %}#}
{##}
{#{% block head %}#}
{#    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">#}
{#{% endblock %}#}
{##}
{#{% block body %}#}
{#    <div class="row" style="margin-top: 20px;">#}
{#        <div class="col"></div>#}
{#        <div class="col-8">#}
{#            <h1>在此上传图片</h1>#}
{#            <form method=post enctype=multipart/form-data>#}
{#                <input type=file name=file class="a-upload div-a">{# 上传多个文件添加：multiple="multiple" #}
                {#                <input type=submit class="button_search" value=上传>#}
                {#                <a href="javascript:" class="a-upload div-a">#}
                {#                    <input type="file" name="file"/>点击这里选择文件{# 上传多个文件添加：multiple="multiple" #}
                {#                </a>#}
{#                <input type=submit class="button_search div-b" value=上传>#}
{#            </form>#}
{#            <br/>#}
{#            {% for message in get_flashed_messages() %}#}
{#                <div class="form-group">#}
{#                    <div class="text-danger">{{ message }}</div>#}
{#                </div>#}
{#            {% endfor %}#}
{#        </div>#}
{#        <div class="col"></div>#}
{#    </div>#}
{#{% endblock %}#}




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>水表系统-首页</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static',filename='bootstrap/bootstrap@4.6.min.css') }}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">水表系统</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">首页<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/history">历史数据</a>
                </li>
                <li class="nav-item" ml-2>
                    <form class="form-inline my-2 my-lg-0" method="GET" action="/search">
                        <input class="form-control mr-sm-2" type="search" placeholder="关键字"
                               aria-label="Search" name="q">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索
                        </button>
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user %}
                    <li class="nav-item">
                        <span class="nav-link">{{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-8">
            <h1>在此上传图片</h1>
            <form method=post enctype=multipart/form-data>
                <input type=file name=file class="a-upload div-a">{# 上传多个文件添加：multiple="multiple" #}
                {#                <input type=submit class="button_search" value=上传>#}
                {#                <a href="javascript:" class="a-upload div-a">#}
                {#                    <input type="file" name="file"/>点击这里选择文件{# 上传多个文件添加：multiple="multiple" #}
                {#                </a>#}
                <input type=submit class="button_search div-b" value=上传>
            </form>
            <br/>
            {% for message in get_flashed_messages() %}
                <div class="form-group">
                    <div class="text-danger">{{ message }}</div>
                </div>
            {% endfor %}
        </div>
        <div class="col"></div>
    </div>
</div>
</body>
</html>

flaskProject/templates/index1.html
{#{% extends "base.html" %}#}
{##}
{#{% block title %}水表系统-首页{% endblock %}#}
{##}
{#{% block head %}#}
{#    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">#}
{#        <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css"/>#}
{#        <script defer src="https://pyscript.net/alpha/pyscript.js"></script>#}
{#{% endblock %}#}
{##}
{#{% block body %}#}
{#    <div class="row" style="margin-top: 20px;">#}
{#        <div class="col"></div>#}
{#        <div class="col-8">#}
{#            <h1>在此上传图片</h1>#}
{#            <form method=post enctype=multipart/form-data>#}
{#                <input type=file name=file class="a-upload div-a">{# 上传多个文件添加：multiple="multiple" #}
{#                                <input type=submit class="button_search" value=上传>#}
{#                                <a href="javascript:" class="a-upload div-a">#}
{#                                    <input type="file" name="file"/>点击这里选择文件{# 上传多个文件添加：multiple="multiple" #}
{#                                </a>#}
{#                <input type=submit class="button_search div-b" value=上传>#}
{##}
{#            </form>#}
{##}
{#            <br/>#}
{#            <form method="get" action="/rec">#}
{#                <button type="submit" class="button_search div-c">识别</button>#}
{#            </form>#}
{##}
{#            <br/>#}
{#            <br/>#}
{#            <br/>#}
{#            {% for message in get_flashed_messages() %}#}
{#                <div class="form-group">#}
{#                    <div class="text-danger">{{ message }}</div>#}
{#                </div>#}
{#            {% endfor %}#}
{#        </div>#}
{#        <div class="col"></div>#}
{#    </div>#}
{#{% endblock %}#}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>水表系统-首页</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static',filename='bootstrap/bootstrap@4.6.min.css') }}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/tmp">水表系统</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/tmp">首页<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/history">历史数据</a>
                </li>
                <li class="nav-item" ml-2>
                    <form class="form-inline my-2 my-lg-0" method="GET" action="/search">
                        <input class="form-control mr-sm-2" type="search" placeholder="关键字"
                               aria-label="Search" name="q">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索
                        </button>
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user %}
                    <li class="nav-item">
                        <span class="nav-link">{{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-8">
            <h1>在此上传图片</h1>
            <form method=post enctype=multipart/form-data>
                <input type=file name=file class="a-upload div-a" multiple="multiple">{# 上传多个文件添加：multiple="multiple"
{#                <input type=submit class="button_search" value=上传>#}
                {#                <a href="javascript:" class="a-upload div-a">#}
                {#                    <input type="file" name="file"/>点击这里选择文件{# 上传多个文件添加：multiple="multiple"#}
                {#                </a>#}
                <input type=submit class="button_search div-b" value=上传>
            </form>

            <br/>
            <form method="get" action="/rec">
                <button type="submit" class="button_search div-c">识别</button>
            </form>

            <br/>
            <br/>
            <br/>
            {% for message in get_flashed_messages() %}
                <div class="form-group">
                    <div class="text-danger">{{ message }}</div>
                </div>
            {% endfor %}
        </div>
        <div class="col"></div>
    </div>
</div>
</body>
</html>

flaskProject/templates/login.html
{% extends "base.html" %}

{% block title %}水表系统-登录{% endblock %}

{% block head %}

{% endblock %}

{% block body %}
    <div class="row mt-4">
        <div class="col"></div>
        <div class="col">
            <form action="{{ url_for("user.login") }}" method="POST">
                <div class="form-group">
                    <label for="exampleInputEmail1">邮箱</label>
                    <input type="email" class="form-control" id="exampleInputEmail1"
                           aria-describedby="emailHelp" name="email">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" name="password" class="form-control"
                           id="exampleInputPassword1">
                </div>

                {% for message in get_flashed_messages() %}
                    <div class="form-group">
                        <div class="text-danger">{{ message }}</div>
                    </div>
                {% endfor %}

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">立即登录</button>
                </div>
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

flaskProject/templates/register.html
{% extends "base.html" %}

{% block title %}水表系统-注册{% endblock %}

{% block head %}
    <script src="{{ url_for('static',filename='jquery/jquery.3.6.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/register.js') }}"></script>
{% endblock %}


{% block body %}
    <div class="row mt-4">
        <div class="col"></div>
        <div class="col">
            <form method="POST" action="{{ url_for('user.register') }}">
                <div class="form-group">
                    <label for="exampleInputEmail1">邮箱</label>
                    <input type="email" class="form-control" id="exampleInputEmail1"
                           aria-describedby="emailHelp" name="email">
                    <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用途</small>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1">验证码</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="captcha">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button"
                                    id="captcha-btn">获取验证码
                            </button>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1">用户名</label>
                    <input type="text" class="form-control" name="username">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1"
                           name="password">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">确认密码</label>
                    <input type="password" class="form-control" name="password_confirm">
                </div>
                {% for message in get_flashed_messages() %}
                    <div class="form-group">
                        <div class="text-danger">{{ message }}</div>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary btn-block">立即注册</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}